### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by gyh1621** [kingname/MarkdownPicPicker#1]
```
({'hash': 'Fv0tEHpCV4LsNyC_AU7t-KrqMiBJ', 'key': '2016-07-14-00-32-33.png'}, status_code:200, exception:None, text_body:{"hash":"Fv0tEHpCV4LsNyC_AU7t-KrqMiBJ","key":"2016-07-14-00-32-33.png"}, _ResponseInfo__response:<Response [200]>, x_log:s.ph;s.put.tw;s.put.tr;s.put.tw;s.put.tr;s.ph;s.put.tw;s.pu
t.tr;s.ph;PFDS;PFDS;PFDS:2;rs20_2.sel/not found;rdb.g/no such key;DBD/404;v4.get/Document not found;rs21_2.ups;qtbl.ups:2;mc.s;RS:2;rs.put:3;rs-upload.putFile:6;UP:8, req_id:4FIAAOlNszEa52AU)
Traceback (most recent call last):
  File "MarkdownPicPicker.py", line 129, in <module>
    MarkrdownPicPicker()
  File "MarkdownPicPicker.py", line 44, in __init__
    self.upload_picture()
  File "MarkdownPicPicker.py", line 106, in upload_picture
    self.uploader.write_markdown_picture_url(picture_name, link_only=True if self.link_only else False)
TypeError: write_markdown_picture_url() got an unexpected keyword argument 'link_only'
```

图片上传上去了，但是地址没在剪切板里，这个该怎么解决呢？

**Comment by Juddd** [comment]
嗯，我也是情况一下，其实我正想来post一下的。。

**Comment by kingname** [comment]
这个问题的原因很简单，因为你没有更新uploader/QiniuUploader.py这个文件。因为这个文件里面有一个函数的参数也做了修改，因此如果你不更新的话，就会导致报错。

**Comment by kingname** [comment]
[编译好的程序](https://github.com/kingname/MarkdownPicPicker/releases/tag/v0.2)
请直接下载编译好的程序，从而避免不熟悉代码而导致修改出问题。
