### ISSUE TITLE
Network connection failed

### ISSUE THREAD

**Issue by cposture** [kingname/MarkdownPicPicker#5]
There has no server proxy for access to network，so it will occur connection exception，just like the following:

```
Traceback (most recent call last):
  File "site-packages\requests\packages\urllib3\connection.py", line 142, in _ne                                                                                                 w_conn
  File "site-packages\requests\packages\urllib3\util\connection.py", line 91, in                                                                                                  create_connection
  File "site-packages\requests\packages\urllib3\util\connection.py", line 81, in                                                                                                  create_connection
TimeoutError: [WinError 10060]
```

![](https://cloud.githubusercontent.com/assets/8305198/17835783/2d1a0948-67ae-11e6-9423-1c8333604ba5.png)

**Comment by kingname** [comment]
OK，I will add the proxy to MarkdownPicPicker in the next release version.

**Comment by kingname** [comment]
As we discussed, this is not a problem.
You can solve it by setting the global proxy.
And this problem is a seldom issue.
